#!/bin/bash
CLEANED=/home/abrahamphilip/projects/py-dealer/nltk/cleaned
cores=$1
lines=$(cat $CLEANED | wc -l)
# rounding up truncating arithmetic
split=$((($lines + $cores - 1) / $cores))
split -l $split $CLEANED
